snapshot 2026-10-09T17:49:37.092724+00:00

diff --git a/src/usr/bin/google_set_multiqueue b/src/usr/bin/google_set_multiqueue
--- a/src/usr/bin/google_set_multiqueue
+++ b/src/usr/bin/google_set_multiqueue
@@ -48,19 +48,32 @@ fi
 
 function get_metadata() {
   local path="$1"
-  curl -s -m 1 -H "Metadata-Flavor: Google" "http://${METADATA_SERVER}/computeMetadata/v1/${path}"
+  curl -s \
+    --fail \
+    --retry 4 \
+    --retry-connrefused \
+    --retry-max-time 15 \
+    --connect-timeout 1 \
+    --max-time 2 \
+    -H "Metadata-Flavor: Google" \
+    "http://${METADATA_SERVER}/computeMetadata/v1/${path}"
 }
 
 A4X_ALL_CPUS_MASK="0000ffff,ffffffff,ffffffff,ffffffff,ffffffff"
-A4X_RX_RING_LENGTH="2048"
-A4X_TX_RING_LENGTH="1024"
+IDPF_RX_RING_LENGTH="4096"
+IDPF_TX_RING_LENGTH="4096"
+IDPF_DEFAULT_RING_LENGTH="512"
 
 function is_decimal_int() {
   [ "${1}" -eq "${1}" ] > /dev/null 2>&1
 }
 
-function set_channels() {
+function set_combined_channels() {
   ethtool -L "${1}" combined "${2}" > /dev/null 2>&1
+}
+
+function set_rx_tx_ring_length() {
+  ethtool -G "${1}" rx "${2}" tx "${3}" > /dev/null 2>&1
 }
 
 function set_irq_range_idpf() {
@@ -157,10 +170,16 @@ function set_irq_range_gve() {
 # returns 0 (success) if the all the interfaces contains pnic_id on the Metadats server.
 function contains_pnic_ids() {
   local interfaces=$(get_metadata "instance/network-interfaces/")
+
+  # If there are somehow no interfaces, then we don't have any pnic ids!
+  if [[ -z "$interfaces" ]]; then
+    return 1
+  fi
+
   for interface in $interfaces; do
     echo "Interface: $interface"
 
-    network_interfaces_mds_attributes=$(get_metadata "instance/network-interfaces/$interface/")
+    local network_interfaces_mds_attributes=$(get_metadata "instance/network-interfaces/$interface/")
 
     if ! echo "$network_interfaces_mds_attributes" | grep -q "physical-nic-id"; then
       echo "physical-nic-id NOT found in interface $interface"
@@ -183,8 +202,8 @@ function is_multinic_accelerator_platform() {
   || "$machine_type" == *"a3-edgegpu-8g"* \
   || "$machine_type" == *"a3-ultragpu-"* \
   || "$machine_type" == *"a4-highgpu-"* \
-  || "$machine_type" == *"a4x-highgpu-"* \
-  || "$machine_type" == *"a4x-maxgpu-"* \
+  || "$machine_type" == *"a4x-"* \
+  || "$machine_type" == *"a5x-"* \
   || "$machine_type" == *"c4n-"* \
   || "$machine_type" == *"c4x-"* ]] || return 1
   return 0
@@ -331,6 +350,12 @@ function set_xps_affinity() {
   local numa="$1"
   local cpus=("${@:2}")
 
+  if [[ "$machine_type" == *"a4x-maxgpu-"* || "$machine_type" == *"a5x-"* ]]; then
+    # We find that setting XPS on these platforms degrades performance.
+    echo "skipping set_xps_affinity"
+    return
+  fi
+
   total_vcpus=${#cpus[@]}
   nics_string=$(get_network_interfaces)
 
@@ -339,6 +364,7 @@ function set_xps_affinity() {
     tx_queue_count=$(ls -1 ${ROOT_DIR}sys/class/net/"$nic"/queues/ | grep tx | wc -l)
 
     if [[ "$machine_type" == *"a4x-"* ]]; then
+      # Implicitly excluding a4x-maxgpu- due to earlier check.
       # All queues on a4x get the full mask.
       for (( queue=0; queue<tx_queue_count; queue++ )); do
         echo "${A4X_ALL_CPUS_MASK}" > "${ROOT_DIR}sys/class/net/$nic/queues/tx-$queue/xps_cpus"
@@ -396,15 +422,141 @@ function set_xps_affinity() {
   done
 }
 
-# Special features only for x4.
-function apply_x4_configs() {
-  echo "Configuring special features for x4."
+function try_set_idpf_channels() {
+  local -r eth_dev="$1"
+  if ! errormsg=$(ethtool -l "$eth_dev" 2>&1); then
+      echo "\`ethtool -l\` failed for $eth_dev: $errormsg."
+    return 1
+  fi
+
+  # Sample output follows.
+  #
+  # Channel parameters for eth0:
+  #  Pre-set maximums:
+  #  RX:		16
+  #  TX:		16
+  #  Other:		1
+  #  Combined:	16
+  #  Current hardware settings:
+  #  RX:		0
+  #  TX:		0
+  #  Other:		1
+  #  Combined:	16
+
+  num_max_channels=$(ethtool -l "$eth_dev" | grep -m 1 Combined | awk '{print $NF}')
+  if [[ -z "${num_max_channels}" || "${num_max_channels}" -eq "1" ]]; then
+    echo "num_max_channels is n/a, skipping set channels for $eth_dev"
+    return 1
+  fi
+  if ! is_decimal_int "$num_max_channels"; then
+    echo "Setting channels for $eth_dev: $num_max_channels is not a decimal int."
+    return 1
+  fi
+  if ! set_combined_channels "$eth_dev" "$num_max_channels"; then
+    echo "Failed to set channels for $eth_dev to $num_max_channels."
+    return 1
+  fi
+  echo "Set channels for $eth_dev to $num_max_channels."
+  return 0
+}
+
+function try_set_idpf_ring_length() {
+  local -r eth_dev="$1"
+  if ! errormsg=$(ethtool -g "$eth_dev" 2>&1); then
+    echo "\`ethtool -g\` failed for $eth_dev: $errormsg."
+    return 1
+  fi
+  local -r ethtool_output=$(ethtool -g "$eth_dev")
+  # Matching assumes that max is listed first, then current, and that there
+  # are no other matches in the output.
+  # Sample output follows.
+  #
+  # Ring parameters for eth0:
+  # Pre-set maximums:
+  # RX:			8128
+  # RX Mini:		n/a
+  # RX Jumbo:		n/a
+  # TX:			8160
+  # TX push buff len:	n/a
+  # Current hardware settings:
+  # RX:			512
+  # RX Mini:		n/a
+  # RX Jumbo:		n/a
+  # TX:			512
+  # RX Buf Len:		n/a
+  # CQE Size:		n/a
+  # TX Push:		off
+  # RX Push:		off
+  # TX push buff len:	n/a
+  # TCP data split:		on
+
+  local -r max_rx=$(echo $"$ethtool_output" | awk '/RX:/{print $2; exit}')
+  local -r max_tx=$(echo $"$ethtool_output" | awk '/TX:/{print $2; exit}')
+  local -r current_rx=$(echo $"$ethtool_output" | awk '/RX:/{last=$2} END{print last}')
+  local -r current_tx=$(echo $"$ethtool_output" | awk '/TX:/{last=$2} END{print last}')
+  if [[ $max_rx -lt $IDPF_RX_RING_LENGTH ]]; then
+    echo "Reported max RX ring length for $eth_dev is $max_rx, which is less than the desired $IDPF_RX_RING_LENGTH."
+    return 1
+  fi
+  if [[ $max_tx -lt $IDPF_TX_RING_LENGTH ]]; then
+    echo "Reported max TX ring length for $eth_dev is $max_tx, which is less than the desired $IDPF_TX_RING_LENGTH."
+    return 1
+  fi
+  if [[ $current_rx -ne $IDPF_DEFAULT_RING_LENGTH || $current_tx -ne $IDPF_DEFAULT_RING_LENGTH ]]; then
+    echo "Current RX/TX ($current_rx/$current_tx) ring len for $eth_dev is not the default ($IDPF_DEFAULT_RING_LENGTH). Not setting ring length."
+    return 0
+  fi
+
+  if ! set_rx_tx_ring_length "$eth_dev" "$IDPF_RX_RING_LENGTH" "$IDPF_TX_RING_LENGTH"; then
+    echo "Failed to set ring length for $eth_dev to $IDPF_RX_RING_LENGTH (RX) and $IDPF_TX_RING_LENGTH (TX)."
+    return 1
+  fi
+
+  echo "Set ring length for $eth_dev to $IDPF_RX_RING_LENGTH (RX) and $IDPF_TX_RING_LENGTH (TX)."
+  return 0
+}
+
+# Enable max supported queue count for IDPF devices.
+function set_idpf_configs() {
+  if [ ! -x "$(command -v ethtool)" ]; then
+    echo "ethtool not found: unable to configure device queue counts"
+    return
+  fi
+
+  for eth_dev in $(get_pci_network_interfaces); do
+    if ! is_idpf "$eth_dev"; then
+      continue
+    fi
+    if ! try_set_idpf_channels "$eth_dev"; then
+      echo "Failed to set channels for $eth_dev"
+    fi
+    if ! try_set_idpf_ring_length "$eth_dev"; then
+      echo "Failed to set ring length for $eth_dev"
+    fi
+  done
+}
+
+# Special features only for x series machines.
+function apply_xseries_configs() {
+  echo "Configuring special features for x series machines."
+
+  local -r rps_per_queue_flow_cnt=16384
+  local -r pci_nics=$(get_pci_network_interfaces)
+  local num_rx_queues=0
+  for nic_name in $pci_nics; do
+    if is_idpf "$nic_name"; then
+      queues=(${ROOT_DIR}sys/class/net/"$nic_name"/queues/rx-*)
+      if [[ -e "${queues[0]}" ]]; then
+        num_rx_queues=$((num_rx_queues + ${#queues[@]}))
+      fi
+    fi
+  done
 
   # Globally enable RFS to reduce load on CPUs handling softirqs
   # (still need per-queue enable).
-  sysctl net.core.rps_sock_flow_entries=262144
+  sysctl net.core.rps_sock_flow_entries=$((num_rx_queues * rps_per_queue_flow_cnt))
 
-  for nic_name in $(get_pci_network_interfaces); do
+  for nic_name in $pci_nics; do
     if ! is_idpf "$nic_name"; then
       continue
     fi
@@ -417,8 +569,7 @@ function apply_x4_configs() {
     ethtool -C "$nic_name" adaptive-tx off adaptive-rx off rx-usecs 20 tx-usecs 50
 
     # Per-queue flow count for RFS.
-    # Assumes 16 queues -> 262144 / 16 = 16384.
-    echo 16384 | tee ${ROOT_DIR}sys/class/net/"$nic_name"/queues/rx-*/rps_flow_cnt > /dev/null
+    echo "$rps_per_queue_flow_cnt" | tee ${ROOT_DIR}sys/class/net/"$nic_name"/queues/rx-*/rps_flow_cnt > /dev/null
   done
 
   # Distribute IRQs across CPUs.
@@ -431,8 +582,8 @@ echo "Running $(basename $0)."
 machine_type=$(get_metadata "instance/machine-type")
 echo "Machine type: $machine_type"
 
-if [[ "$machine_type" =~ "x4-" ]]; then
-  apply_x4_configs
+if [[ "$machine_type" =~ x[4-5]- ]]; then
+  apply_xseries_configs
   exit 0
 fi
 
@@ -440,32 +591,7 @@ VIRTIO_NET_DEVS=${ROOT_DIR}sys/bus/virtio/drivers/virtio_net/virtio*
 is_multinic_accelerator_platform
 IS_MULTINIC_ACCELERATOR_PLATFORM=$?
 
-# Loop through all the virtionet devices and enable multi-queue
-if [ -x "$(command -v ethtool)" ]; then
-  for dev in $VIRTIO_NET_DEVS; do
-    ETH_DEVS=${dev}/net/*
-    for eth_dev in $ETH_DEVS; do
-      eth_dev=$(basename "$eth_dev")
-      if ! errormsg=$(ethtool -l "$eth_dev" 2>&1); then
-        echo "ethtool says that $eth_dev does not support virtionet multiqueue: $errormsg."
-        continue
-      fi
-      num_max_channels=$(ethtool -l "$eth_dev" | grep -m 1 Combined | cut -f2)
-      if [[ -n "${num_max_channels}" || "${num_max_channels}" -eq "1" ]]; then
-        echo "num_max_channels is n/a, skipping set channels for $eth_dev"
-        continue
-      fi
-      if is_decimal_int "$num_max_channels" && \
-        set_channels "$eth_dev" "$num_max_channels"; then
-        echo "Set channels for $eth_dev to $num_max_channels."
-      else
-        echo "Could not set channels for $eth_dev to $num_max_channels."
-      fi
-    done
-  done
-else
-  echo "ethtool not found: cannot configure virtionet multiqueue."
-fi
+set_idpf_configs
 
 for dev in $VIRTIO_NET_DEVS
 do
@@ -557,12 +683,6 @@ for ((node=0; node<num_numa_nodes; node++)); do
     nic_numa_node=$(cat ${ROOT_DIR}sys/class/net/"$nic_name"/device/numa_node)
     if [[ $nic_numa_node -ne $node ]]; then
       continue
-    fi
-
-    # For IDPF at least, we need to reconfigure ring size before setting IRQ affinity,
-    # since adjusting the ring size destroys the IRQ affinity settings.
-    if [[ $machine_type == *"a4x-maxgpu-"* ]]; then
-      ethtool -G "$nic_name" rx "$A4X_RX_RING_LENGTH" tx "$A4X_TX_RING_LENGTH"
     fi
 
     # For non-gvnic/idpf devices (e.g. mlx5), the IRQ bindings will be handled by the device's driver.
