snapshot 2025-11-07T15:30:29.482640+00:00

diff --git a/src/usr/bin/google_set_multiqueue b/src/usr/bin/google_set_multiqueue
--- a/src/usr/bin/google_set_multiqueue
+++ b/src/usr/bin/google_set_multiqueue
@@ -46,7 +46,8 @@ function set_channels() {
 
 function set_irq_range() {
   local -r nic="$1"
-  local bind_cores_begin="$2"
+  local bind_cores_index="$2"
+  local irq_ranges=("${@:3}")
 
   # The user may not have this $nic configured on their VM, if not, just skip
   # it, no need to error out.
@@ -60,11 +61,9 @@ function set_irq_range() {
   # queues while the number of IRQs stands for the max queues. The number of
   # initial queues should be always less than or equal to that of the max
   # queues.
-  core=$bind_cores_begin
   num_irqs=$(( $(ls /sys/class/net/"$nic"/device/msi_irqs | wc -l) / 2 ))
   num_q=$(ls -1 /sys/class/net/"$nic"/queues/ | grep rx | wc -l)
-
-  echo "Setting irq binding for "$nic" to core [$core - $((core + num_q - 1))] ..."
+  echo "Setting irq binding for "$nic" to core ["${irq_ranges[${bind_cores_index}]}" - "${irq_ranges[$((bind_cores_index + num_q - 1))]}] ... >&2
 
   irqs=($(ls /sys/class/net/"$nic"/device/msi_irqs | sort -g))
   for ((irq = 0; irq < "$num_irqs"; irq++)); do
@@ -73,42 +72,67 @@ function set_irq_range() {
 
     # Only allocate $num_q cores to the IRQs and queues. If the number of IRQs
     # is more than that of queues, the CPUs will be wrapped around.
-    core=$(( bind_cores_begin + irq % num_q ))
+    core="${irq_ranges[${bind_cores_index}]}"
+    ((bind_cores_index++))
 
     # this is GVE's TX irq. See gve_tx_idx_to_ntfy().
-    echo "$core" > /proc/irq/"$tx_irq"/smp_affinity_list
+    echo "$core" > "/proc/irq/${tx_irq}/smp_affinity_list"
+    echo "tx_irq: ${tx_irq}, assigned irq core: $(cat "/proc/irq/${tx_irq}/smp_affinity_list")" >&2
 
     # this is GVE's RX irq. See gve_rx_idx_to_ntfy().
-    echo "$core" > /proc/irq/"$rx_irq"/smp_affinity_list
+    echo "$core" > "/proc/irq/${rx_irq}/smp_affinity_list"
+    echo "rx_irq: ${rx_irq}, assigned irq core: $(cat "/proc/irq/${rx_irq}/smp_affinity_list")" >&2
+
 
     # Check if the queue exists at present because the number of IRQs equals
     # the max number of queues allocated and could be greater than the current
     # number of queues.
     tx_queue=/sys/class/net/"$nic"/queues/tx-"$irq"
     if ls $tx_queue 1> /dev/null 2>&1; then
-      # XPS (Transmit Packet Steering) allows a core to decide which queue to
-      # select if its mask is found in one of the queue's xps_cpus
-      cp /proc/irq/"$tx_irq"/smp_affinity $tx_queue/xps_cpus
-
-      echo -en "$nic:q-$irq: \ttx: irq $tx_irq bind to $core \trx: irq $rx_irq bind to $core"
-      echo -e " \txps_cpus bind to $(cat $tx_queue/xps_cpus)"
+      echo -en "$nic:q-$irq: \ttx: irq $tx_irq bind to $core \trx: irq $rx_irq bind to $core" >&2
+      echo -e " \txps_cpus bind to $(cat $tx_queue/xps_cpus)" >&2
     else
-      echo -e "$nic:q-$irq: \ttx: irq $tx_irq bind to $core \trx: irq $rx_irq bind to $core"
+      echo -e "$nic:q-$irq: \ttx: irq $tx_irq bind to $core \trx: irq $rx_irq bind to $core" >&2
     fi
 
   done
+
+  echo "$bind_cores_index"
 }
 
-# returns 0 (success) if it's running on a3 or a3plus platform.
-function is_a3_platform() {
+# returns 0 (success) if the all the interfaces contains pnic_id on the Metadats server.
+function contains_pnic_ids() {
+  while IFS= read -r interface; do
+    echo "Interface: $interface"
+
+    network_interfaces_mds_attributes=$(curl -m 1 -H "Metadata-Flavor: Google" \
+      "http://169.254.169.254/computeMetadata/v1/instance/network-interfaces/$interface/")
+
+    if ! echo "$network_interfaces_mds_attributes" | grep -q "physical-nic-id"; then
+      echo "physical-nic-id NOT found in interface $interface"
+      return 1
+    fi
+  done < <(curl -m 1 -H "Metadata-Flavor: Google" http://169.254.169.254/computeMetadata/v1/instance/network-interfaces/)
+
+  return 0
+}
+
+# returns 0 (success) if the platform is a multinic accelerator platform.
+function is_multinic_accelerator_platform() {
+  contains_pnic_ids
+  CONTAINS_PNIC_IDS=$?
+
   machine_type=$(curl -m 1 -H "Metadata-Flavor: Google" \
     http://169.254.169.254/computeMetadata/v1/instance/machine-type)
 
-  [[ "$machine_type" == *"a3-highgpu-8g"* \
+  [[ $CONTAINS_PNIC_IDS -eq 0 \
+  || "$machine_type" == *"a3-highgpu-8g"* \
   || "$machine_type" == *"a3-ultragpu-8g"* \
   || "$machine_type" == *"a3-megagpu-8g"* \
   || "$machine_type" == *"a3-edgegpu-8g"* \
-  || "$machine_type" == *"a3-ultragpu-"* ]] || return 1
+  || "$machine_type" == *"a3-ultragpu-"* \
+  || "$machine_type" == *"a4-highgpu-"* \
+  || "$machine_type" == *"a4x-highgpu-"* ]] || return 1
   return 0
 }
 
@@ -146,10 +170,6 @@ function get_vcpu_ranges_on_accelerator_platform {
   numa0_irq_range1="${numa0_irq_range[0]#*,}"
 
   numa0_irq_range0_start=$(echo "$numa0_irq_range0" | cut -d '-' -f 1)
-  # Avoid setting binding IRQ on vCPU 0 as it is a busy vCPU being heavily
-  # used by the system.
-  numa0_irq_range0_start=$((numa0_irq_range0_start + 1))
-  
   numa0_irq_range0_end=$(echo "$numa0_irq_range0" | cut -d '-' -f 2)
   numa0_irq_range1_start=$(echo "$numa0_irq_range1" | cut -d '-' -f 1)
   numa0_irq_range1_end=$(echo "$numa0_irq_range1" | cut -d '-' -f 2)
@@ -175,10 +195,149 @@ function get_vcpu_ranges_on_accelerator_platform {
   "$numa1_irq_range1_end")
 }
 
+function unpack_cpu_ranges() {
+    local input_ranges=($1)
+    local -n irq_ranges="$2"
+    for ((i=0; i<${#input_ranges[@]}; i+=2)); do
+        local start="${input_ranges[$i]}"
+        local end="${input_ranges[$((i+1))]}"
+
+        for ((core_number=start; core_number<=end; core_number++)); do
+            irq_ranges+=("$core_number")
+        done
+    done
+}
+
+# Converts a hexadecimal bitmap to rangelist
+# ex. bitmap=00000000,00000000,00fff000,000003ff CPUs=0-9,44-55
+function bitmap_to_rangelist() { # bitmap
+  local bitmap="${1:-}" # must be non empty, only hex digits and commas
+
+  [[ "${bitmap}" =~ ^[0-9a-fA-F,]+$ ]] || return 1
+  bitmap="${bitmap//,/}"                # remove commas
+
+  local comma='' ret=''
+  local bit=0 l=-1 h=0 # current bit and range boundaries
+  local i j # process one character at a time starting from right (low index)
+  for ((i = ${#bitmap} - 1; i >= 0; i--)); do
+    local cur="0x${bitmap:${i}:1}"
+    for ((j = 0; j < 4; j++, bit++, cur >>= 1)); do
+      (( cur & 1 )) || continue                             # bit is 0
+      (( l < 0 )) && (( l = bit, h = bit, 1 )) && continue  # first bit
+      (( bit == h + 1 )) && (( h = bit, 1 )) && continue    # extend range
+      ret+="${comma}${l}" ; (( l != h )) && ret+="-${h}"    # add range
+      (( l = bit, h = bit ))                                # start new interval
+      comma=","
+    done
+  done
+  (( l < 0 )) && return
+  ret+="${comma}${l}"; (( l != h )) && ret+="-${h}"         # add final entry
+  echo $ret
+}
+
+# Converts a list of CPUs to a hexadecimal bitmap
+# ex. CPUs=[0,1,2,3,4,5,6,7,8,9,44,45,46,47,48,49,50,51,52,53,54,55]
+# bitmap=00000000,00000000,00fff000,000003ff
+function rangelist_to_bitmap() { # list highest_cpu
+  local ranges="${1:-}" # can be empty, only digits, commas and dash
+  local highest=${2:-1} # highest CPU
+  [[ "${ranges}" =~ ^[0-9,-]*$ ]] || return 1
+  ranges="${ranges//,/ }"       # replace comma with space
+
+  local digits=()
+  local range i l h
+  for range in $ranges; do
+    read l h <<< $(echo ${range/-/ })
+    [[ -z "$h" ]] && h=l
+    for ((i = l; i <= h; i++)) { (( digits[i / 4] |= 1 << (i & 3) )); }
+    (( highest = h > highest ? h : highest))
+  done
+
+  # Print in reverse order with commas
+  local ret="" hex="0123456789abcdef"
+  (( h = (highest + 31) / 32 * 8 )) # make a multiple of 32 CPUs
+  for (( i = h - 1; i >= 0; i--)) ; do
+    ret+="${hex:${digits[$i]}:1}"
+    (( i & 7 || i == 0)) || ret+=","
+  done
+  echo $ret
+}
+
+# Returns all the network interface names excluding "lo"
+get_network_interfaces() {
+    local network_interfaces=()
+
+    for nic_dir in /sys/class/net/*; do
+        local nic_name=$(basename "${nic_dir}")
+
+        if [[ "${nic_name}" == "lo" || ! -e "${nic_dir}/device" ]]; then
+            continue
+        fi
+
+        network_interfaces+=("${nic_name}")
+    done
+
+    echo "${network_interfaces[@]}"
+}
+
+# For XPS affinity configuration, we'd do the following assignment:
+# 1. For each interface, divide the queues into two halves
+# 2. Evenly distribute the vCPUs on NUMA0 to the first half of the queues
+# 3. Evenly distribute the vCPUs on NUMA1 to the second half of the queues
+# This function will have to be called once for each NUMA.
+function set_xps_affinity() {
+  local numa="$1"
+  local cpus=("${@:2}")
+
+  total_vcpus=${#cpus[@]}
+  num_numa_nodes=2
+  nics_string=$(get_network_interfaces)
+
+  IFS=' ' read -r -a nics <<< "$nics_string"
+  for nic in "${nics[@]}"; do
+    tx_queue_count=$(ls -1 /sys/class/net/"$nic"/queues/ | grep tx | wc -l)
+
+    # the number of queues to assign CPUs for this NUMA node.
+    queues_per_numa=$(( tx_queue_count / num_numa_nodes ))
+
+    # the number of CPUs to assign per queue
+    cpus_per_queue=$(( total_vcpus / queues_per_numa))
+
+    echo "nic=$nic tx_queue_count=$tx_queue_count queues_per_numa=$queues_per_numa cpus_per_queue=$cpus_per_queue"
+
+    cpu_index=0
+    queue_offset=$(( queues_per_numa*numa ))
+    for (( queue=queue_offset; queue<queue_offset+queues_per_numa; queue+=1 )); do
+      xps_path=/sys/class/net/$nic/queues/tx-$queue/xps_cpus
+      xps_cpus=""
+
+      # Assign all the remaining CPUs to the last queue
+      if [[ queue -eq $(( queue_offset + queues_per_numa - 1 )) ]]; then
+        cpus_per_queue=$(( total_vcpus - cpu_index ))
+      fi 
+
+      for (( i=0; i<cpus_per_queue; i+=1 )); do
+        xps_cpus+="${cpus[cpu_index]},"
+        cpu_index=$(( cpu_index + 1 ))
+      done
+
+      # remove the last ","
+      xps_cpus="${xps_cpus%,}"
+      cpu_mask=$(rangelist_to_bitmap $xps_cpus $(nproc))
+      echo ${cpu_mask} > $xps_path
+      printf "Queue %d XPS_PATH=%s assigned CPUs=%s cpu_mask=%s\n" \
+        "$queue" \
+        "$xps_path" \
+        "$(bitmap_to_rangelist "$cpu_mask")" \
+        "$cpu_mask"
+    done 
+  done
+}
+
 echo "Running $(basename $0)."
 VIRTIO_NET_DEVS=/sys/bus/virtio/drivers/virtio_net/virtio*
-is_a3_platform
-IS_A3_PLATFORM=$?
+is_multinic_accelerator_platform
+IS_MULTINIC_ACCELERATOR_PLATFORM=$?
 
 # Loop through all the virtionet devices and enable multi-queue
 if [ -x "$(command -v ethtool)" ]; then
@@ -260,54 +419,29 @@ for i in /proc/irq/*; do
   fi
 done
 
-XPS=/sys/class/net/e*/queues/tx*/xps_cpus
-num_cpus=$(nproc)
-[[ $num_cpus -gt 63 ]] && num_cpus=63
+vcpu_ranges=()
+get_vcpu_ranges_on_accelerator_platform vcpu_ranges
 
-num_queues=0
-for q in $XPS; do
-  interface=$(echo "$q" | grep -oP 'net/\K[^/]+')
-  if [[ $IS_A3_PLATFORM == 0 ]] && ! $(is_gvnic "$interface"); then
-    continue
-  fi
-  num_queues=$((num_queues + 1))
-done
+packed_numa0_vcpu_ranges=(
+  "${vcpu_ranges[0]} ${vcpu_ranges[1]} ${vcpu_ranges[2]} ${vcpu_ranges[3]}"
+)
+packed_numa1_vcpu_ranges=(
+  "${vcpu_ranges[4]} ${vcpu_ranges[5]} ${vcpu_ranges[6]} ${vcpu_ranges[7]}"
+)
+declare -a numa0_vcpu_ranges
+unpack_cpu_ranges "${packed_numa0_vcpu_ranges[0]}" numa0_vcpu_ranges
+declare -a numa1_vcpu_ranges
+unpack_cpu_ranges "${packed_numa1_vcpu_ranges[0]}" numa1_vcpu_ranges
 
-# If we have more CPUs than queues, then stripe CPUs across tx affinity
-# as CPUNumber % queue_count.
-for q in $XPS; do
-  interface=$(echo "$q" | grep -oP 'net/\K[^/]+')
-  if [[ $IS_A3_PLATFORM == 0 ]] && ! $(is_gvnic "$interface"); then
-    continue
-  fi
+echo -e "\nConfiguring XPS affinity for devices on NUMA 0"
+echo -e "vCPUs on NUMA0 [${vcpu_ranges[0]}-${vcpu_ranges[1]}], [${vcpu_ranges[2]}-${vcpu_ranges[3]}]"
+set_xps_affinity 0 "${numa0_vcpu_ranges[@]}"
 
-  queue_re=".*tx-([0-9]+).*$"
-  if [[ "$q" =~ ${queue_re} ]]; then
-    queue_num=${BASH_REMATCH[1]}
-  fi
+echo -e "\nConfiguring XPS affinity for devices on NUMA 1"
+echo -e "vCPUs on NUMA1 [${vcpu_ranges[4]}-${vcpu_ranges[5]}], [${vcpu_ranges[6]}-${vcpu_ranges[7]}]"
+set_xps_affinity 1 "${numa1_vcpu_ranges[@]}"
 
-  xps=0
-  for cpu in `seq $queue_num $num_queues $((num_cpus - 1))`; do
-    xps=$((xps | (1 << cpu)))
-  done
-
-  # Linux xps_cpus requires a hex number with commas every 32 bits. It ignores
-  # all bits above # cpus, so write a list of comma separated 32 bit hex values
-  # with a comma between dwords.
-  xps_dwords=()
-  for i in $(seq 0 $(((num_cpus - 1) / 32)))
-  do
-    xps_dwords=(`printf "%08x" $((xps & 0xffffffff))` "${xps_dwords[@]}")
-    xps=$((xps >> 32))
-  done
-  xps_string=$(IFS=, ; echo "${xps_dwords[*]}")
-
-
-  echo ${xps_string} > $q
-  printf "Queue %d XPS=%s for %s\n" $queue_num `cat $q` $q
-done | sort -n -k2
-
-if [[ ! $IS_A3_PLATFORM == 0 ]]; then
+if [[ ! $IS_MULTINIC_ACCELERATOR_PLATFORM == 0 ]]; then
   exit
 fi
 
@@ -330,12 +464,21 @@ fi
 # enp134s0
 # enp140s0
 
-irq_ranges=()
-get_vcpu_ranges_on_accelerator_platform irq_ranges
-echo "Binding vCPUs on NUMA0 [${irq_ranges[0]} ${irq_ranges[1]}], [${irq_ranges[2]} ${irq_ranges[3]}]}"
-echo "Binding vCPUs on NUMA1 [${irq_ranges[4]} ${irq_ranges[5]}], [${irq_ranges[6]} ${irq_ranges[7]}]}"
+# Avoid setting binding IRQ on vCPU 0 as it is a busy vCPU being heavily
+# used by the system.
+packed_numa0_irq_ranges=(
+  "$((vcpu_ranges[0] + 1)) ${vcpu_ranges[1]} ${vcpu_ranges[2]} ${vcpu_ranges[3]}"
+)
+packed_numa1_irq_ranges=(
+  "${vcpu_ranges[4]} ${vcpu_ranges[5]} ${vcpu_ranges[6]} ${vcpu_ranges[7]}"
+)
+declare -a numa0_irq_ranges
+unpack_cpu_ranges "${packed_numa0_irq_ranges[0]}" numa0_irq_ranges
+declare -a numa1_irq_ranges
+unpack_cpu_ranges "${packed_numa1_irq_ranges[0]}" numa1_irq_ranges
 
-numa0_irq_start=${irq_ranges[0]}
+echo -e "\nSetting IRQ affinity with vCPUs on NUMA0 [${numa0_irq_ranges[@]}]"
+bind_cores_index=0
 find /sys/class/net -type l | xargs -L 1 realpath | grep '/sys/devices/pci' | sort | xargs -L 1 basename | while read nic_name; do
   # For non-gvnic devices (e.g. mlx5), the IRQ bindings will be handled by the device's driver.
   if ! is_gvnic "$nic_name"; then
@@ -343,28 +486,18 @@ find /sys/class/net -type l | xargs -L 1 realpath | grep '/sys/devices/pci' | so
     continue
   fi
 
-  echo "$nic_name is Gvnic device, continuing set IRQ on $nic_name ."
+  echo "$nic_name is Gvnic device, continuing set IRQ on $nic_name."
 
   nic_numa_node=$(cat /sys/class/net/"$nic_name"/device/numa_node)
   if [[ $nic_numa_node -ne 0 ]]; then
     continue
   fi
 
-  nic_num_queues=$(ls -1 /sys/class/net/"$nic_name"/queues/ | grep rx | wc -l)
-  bind_cores_begin=$numa0_irq_start
-  bind_cores_end=$((bind_cores_begin + nic_num_queues))
-
-  if [[ $bind_cores_begin -lt ${irq_ranges[1]} ]] && [[ $bind_cores_end -gt ${irq_ranges[1]} ]]; then
-    bind_cores_begin=${irq_ranges[2]}
-    bind_cores_end=$((bind_cores_begin + nic_num_queues))
-  fi
-
-  set_irq_range "$nic_name" "$bind_cores_begin"
-
-  numa0_irq_start=$bind_cores_end
+  bind_cores_index=$(set_irq_range "$nic_name" "$bind_cores_index" "${numa0_irq_ranges[@]}")
 done
 
-numa1_irq_start=${irq_ranges[4]}
+echo -e "\nSetting IRQ affinity with vCPUs on NUMA1 [${numa1_irq_ranges[@]}]"
+bind_cores_index=0
 find /sys/class/net -type l | xargs -L 1 realpath | grep '/sys/devices/pci' | sort | xargs -L 1 basename | while read nic_name; do
   # For non-gvnic devices (e.g. mlx5), the IRQ bindings will be handled by the device's driver.
   if ! is_gvnic "$nic_name"; then
@@ -372,24 +505,13 @@ find /sys/class/net -type l | xargs -L 1 realpath | grep '/sys/devices/pci' | so
     continue
   fi
 
-  echo "$nic_name is Gvnic device, continuing set IRQ on $nic_name ."
+  echo "$nic_name is Gvnic device, continuing set IRQ on $nic_name."
 
   nic_numa_node=$(cat /sys/class/net/"$nic_name"/device/numa_node)
   if [[ $nic_numa_node -ne 1 ]]; then
     continue
   fi
 
-  nic_num_queues=$(ls -1 /sys/class/net/"$nic_name"/queues/ | grep rx | wc -l)
-  bind_cores_begin=$numa1_irq_start
-  bind_cores_end=$((bind_cores_begin + nic_num_queues))
-
-  if [[ $bind_cores_begin -lt ${irq_ranges[5]} ]] && [[ $bind_cores_end -gt ${irq_ranges[5]} ]]; then
-    bind_cores_begin=${irq_ranges[6]}
-    bind_cores_end=$((bind_cores_begin + nic_num_queues))
-  fi
-
-  set_irq_range "$nic_name" "$bind_cores_begin"
-
-  numa1_irq_start=$bind_cores_end
+  bind_cores_index=$(set_irq_range "$nic_name" "$bind_cores_index" "${numa1_irq_ranges[@]}")
 done
   
